# dnadesign/densegen/config.yaml

densegen:
  input_sources:
    - type: "deg2tfbs_pipeline_tfbsfetcher"
      name: "lexA_and_cpxR"
      path: "tfbsbatch_20250630"
    # - type: "deg2tfbs_pipeline_tfbsfetcher"
    #   name: "monotypic_CRP"
    #   path: "tfbsbatch_monotypic_CRP"
  output_dir: "sequences"
  progress_file: "progress_status.yaml"
  solver: "GUROBI"
  diverse_solution: true
  solver_options:
    - "Threads=16"
    - "TimeLimit=10"
  quota: 10000
  sequence_length: 60
  subsample_over_length_budget_by: 120
  # subsample_size: 20  # legacy
  round_robin: true
  arrays_generated_before_resample: 10  
  fixed_elements:
    promoter_constraints:
      # - name: "sigma70_consensus"
      #   upstream: "TTGACA"
      #   downstream: "TATAAT"
      #   spacer_length: [16, 18]
      #   upstream_pos: [10, 40]
      - name: "sigma70_mid_35_strong_10"
        upstream: "ACCGCG"
        downstream: "TATAAT"
        spacer_length: [16, 18]
        upstream_pos: [10, 40]
      # - name: "sigma70_consensus_+"
      #   upstream: "TTGACA"
      #   downstream: "TGTATAATGCT"
      #   spacer_length: [14, 16]
      #   upstream_pos: [10, 100]
      # - name: "sigma70_consensus_-"
      #   upstream: "TTGACA"
      #   downstream: "TCTATAATGAG"
      #   spacer_length: [14, 16]
      #   upstream_pos: [10, 100]
      # - name: "sigma70_mid"
      #   upstream: "ACCGCG"
      #   downstream: "ACCTAA"
      #   spacer_length: [16, 18]
      #   upstream_pos: [10, 100]
      # - name: "sigma70_low"
      #   upstream: "GCAGGT"
      #   downstream: "CCTCGC"
      #   spacer_length: [16, 18]
  unique_tf_only: true
  fill_gap: true
  fill_gap_end: "5prime"
  fill_gc_min: 0.40
  fill_gc_max: 0.60
