"""
--------------------------------------------------------------------------------
dnadesign
src/dnadesign/densegen/tests/meta_fixtures.py

Reusable metadata fixtures for DenseGen tests.

Module Author(s): Eric J. South
--------------------------------------------------------------------------------
"""

from __future__ import annotations


def output_meta(*, library_hash: str, library_index: int) -> dict:
    return {
        "schema_version": "2.8",
        "run_id": "demo",
        "run_root": ".",
        "run_config_path": "config.yaml",
        "run_config_sha256": "dummy",
        "created_at": "2026-01-14T00:00:00+00:00",
        "length": 10,
        "random_seed": 0,
        "policy_pad": "off",
        "policy_sampling": "subsample",
        "policy_solver": "iterate",
        "solver_backend": "CBC",
        "solver_strategy": "iterate",
        "solver_time_limit_seconds": None,
        "solver_threads": None,
        "solver_strands": "double",
        "dense_arrays_version": None,
        "dense_arrays_version_source": "unknown",
        "solver_status": None,
        "solver_objective": None,
        "solver_solve_time_s": None,
        "plan": "demo_plan",
        "tf_list": ["lexA", "cpxR"],
        "tfbs_parts": ["lexA:AAA", "cpxR:CCC"],
        "used_tfbs": ["lexA:AAA", "cpxR:CCC"],
        "used_tfbs_detail": [
            {"tf": "lexA", "tfbs": "AAA", "orientation": "fwd", "offset": 0},
            {"tf": "cpxR", "tfbs": "CCC", "orientation": "fwd", "offset": 4},
        ],
        "used_tf_counts": [{"tf": "lexA", "count": 1}, {"tf": "cpxR", "count": 1}],
        "used_tf_list": ["lexA", "cpxR"],
        "covers_all_tfs_in_solution": True,
        "min_count_per_tf": 0,
        "input_type": "binding_sites",
        "input_name": "demo_input",
        "input_path": "inputs.csv",
        "input_dataset": None,
        "input_root": None,
        "input_mode": "binding_sites",
        "input_pwm_ids": [],
        "input_row_count": 0,
        "input_tf_count": 0,
        "input_tfbs_count": 0,
        "input_tf_tfbs_pair_count": 1,
        "sampling_fraction": 0.5,
        "sampling_fraction_pairs": 0.5,
        "input_pwm_strategy": None,
        "input_pwm_mining_batch_size": None,
        "input_pwm_mining_log_every_batches": None,
        "input_pwm_budget_mode": None,
        "input_pwm_budget_candidates": None,
        "input_pwm_budget_target_tier_fraction": None,
        "input_pwm_budget_max_candidates": None,
        "input_pwm_budget_max_seconds": None,
        "input_pwm_budget_min_candidates": None,
        "input_pwm_budget_growth_factor": None,
        "input_pwm_bgfile": None,
        "input_pwm_keep_all_candidates_debug": None,
        "input_pwm_include_matched_sequence": None,
        "input_pwm_n_sites": None,
        "input_pwm_tier_fractions": None,
        "input_pwm_uniqueness_key": None,
        "input_pwm_selection_policy": None,
        "input_pwm_selection_alpha": None,
        "input_pwm_selection_pool_min_score_norm": None,
        "input_pwm_selection_pool_max_candidates": None,
        "input_pwm_selection_pool_relevance_norm": None,
        "fixed_elements": {"promoter_constraints": [], "side_biases": {"left": [], "right": []}},
        "visual": "",
        "compression_ratio": None,
        "library_size": 2,
        "library_unique_tf_count": 2,
        "library_unique_tfbs_count": 2,
        "sequence_length": 10,
        "promoter_constraint": None,
        "sampling_target_length": 0,
        "sampling_achieved_length": 0,
        "sampling_relaxed_cap": False,
        "sampling_final_cap": None,
        "sampling_pool_strategy": "subsample",
        "sampling_library_size": 2,
        "sampling_library_strategy": "tf_balanced",
        "sampling_iterative_max_libraries": 1,
        "sampling_iterative_min_new_solutions": 0,
        "sampling_library_index": library_index,
        "sampling_library_hash": library_hash,
        "required_regulators": [],
        "min_required_regulators": None,
        "min_count_by_regulator": [],
        "covers_required_regulators": True,
        "pad_used": False,
        "pad_bases": None,
        "pad_end": None,
        "pad_gc_mode": None,
        "pad_gc_min": None,
        "pad_gc_max": None,
        "pad_gc_target_min": None,
        "pad_gc_target_max": None,
        "pad_gc_actual": None,
        "pad_relaxed": None,
        "pad_relaxed_reason": None,
        "pad_attempts": None,
        "gc_total": 0.5,
        "gc_core": 0.5,
    }
