version: 2
input:
  path: /Users/Shockwing/Dropbox/projects/phd/dnadesign/src/dnadesign/usr/datasets/60bp_dual_promoter_cpxR_LexA/records.parquet
  format: parquet
  columns:
    sequence: sequence
    annotations: densegen__used_tfbs_detail
    id: id
  alphabet: DNA
  sample:
    mode: random_rows
    n: 100
    seed: 42
  annotations:
    ambiguous: first
    zero_as_unspecified: true
    offset_mode: auto
    require_non_empty: false
    min_per_record: 1
    require_non_null_cols: null
pipeline:
  plugins:
  - sigma70:
      spacer_min: 15
      spacer_max: 19
      label_mode: inner
      inner_margin_bp: 0.35
      variants:
      - name: sigma70_high
        upstream: TTGACA
        downstream: TATAAT
      - name: sigma70_mid
        upstream: ACCGCG
        downstream: TATAAT
      - name: sigma70_low
        upstream: GCAGGT
        downstream: TATAAT
selection:
  path: inputs/r0_preds.csv
  match_on: id
  column: id
  overlay_column: details
  keep_order: true
  on_missing: warn
style:
  overrides:
    track_spacing: 35.0
    baseline_spacing: 40.0
    padding_y: 5.0
    legend_height_px: 16.0
    legend_pad_px: 10.0
    legend: true
    font_size_seq: 14
    font_size_label: 12
    kmer:
      height_factor: 1.1
      text_v_align: center
      round_px: 5.0
      pad_x_px: 1.025
      fill_alpha: 0.88
    sigma_link_inner_margin_bp: 0.5
    palette:
      sigma: '#969eba'
      tf:cpxr: '#bf812e'
      tf:lexa: '#dfc27e'
output:
  video:
    fmt: mp4
    fps: 6
    frames_per_record: 5
    pauses: {}
    width_px: 1200
    height_px: null
    aspect: '18:4'
  images:
    fmt: png
