"""
--------------------------------------------------------------------------------
<dnadesign project>
dnadesign/densegen/config/__init__.py

Strict, versioned config schema for DenseGen (breaking changes, no fallbacks).

Module Author(s): Eric J. South
Dunlop Lab
--------------------------------------------------------------------------------
"""

from __future__ import annotations

from .base import (
    LATEST_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    ConfigError,
    LoadedConfig,
    RunConfig,
    resolve_outputs_scoped_path,
    resolve_relative_path,
    resolve_run_root,
    resolve_run_scoped_path,
)
from .generation import (
    FixedElements,
    GenerationConfig,
    PlanItem,
    PlanSamplingConfig,
    PlanTemplate,
    PromoterConstraint,
    PromoterMatrix,
    PromoterMatrixPairing,
    RegulatorConstraints,
    RegulatorGroup,
    ResolvedPlanItem,
    SamplingConfig,
    SequenceConstraintAllowlistItem,
    SequenceConstraintAllowSelector,
    SequenceConstraintForbidKmers,
    SequenceConstraintsConfig,
    SideBiases,
    expand_plan_templates,
    normalize_motif_sets,
)
from .inputs import (
    BackgroundPoolFiltersConfig,
    BackgroundPoolFimoExcludeConfig,
    BackgroundPoolGCConfig,
    BackgroundPoolInput,
    BackgroundPoolLengthConfig,
    BackgroundPoolMiningBudgetConfig,
    BackgroundPoolMiningConfig,
    BackgroundPoolSamplingConfig,
    BackgroundPoolUniquenessConfig,
    BindingSitesColumns,
    BindingSitesInput,
    InputConfig,
    PWMArtifactInput,
    PWMArtifactSetInput,
    PWMJasparInput,
    PWMMatrixColumns,
    PWMMatrixCSVInput,
    PWMMemeInput,
    PWMMemeSetInput,
    PWMMiningBudgetConfig,
    PWMMiningConfig,
    PWMSamplingConfig,
    PWMSelectionConfig,
    PWMSelectionPoolConfig,
    PWMTrimmingConfig,
    PWMUniquenessConfig,
    SequenceLibraryInput,
    USRSequencesInput,
)
from .logging import LoggingConfig, LoggingVisualsConfig
from .output import OutputConfig, OutputParquetConfig, OutputSchemaConfig, OutputUSRConfig
from .plots import PlotConfig
from .postprocess import PadConfig, PadGcConfig, PostprocessConfig
from .root import DenseGenConfig, RootConfig, load_config
from .runtime import RuntimeConfig
from .solver import SolverConfig

__all__ = [
    "BackgroundPoolFiltersConfig",
    "BackgroundPoolFimoExcludeConfig",
    "BackgroundPoolGCConfig",
    "BackgroundPoolInput",
    "BackgroundPoolLengthConfig",
    "BackgroundPoolMiningBudgetConfig",
    "BackgroundPoolMiningConfig",
    "BackgroundPoolSamplingConfig",
    "BackgroundPoolUniquenessConfig",
    "BindingSitesColumns",
    "BindingSitesInput",
    "ConfigError",
    "DenseGenConfig",
    "FixedElements",
    "GenerationConfig",
    "InputConfig",
    "LATEST_SCHEMA_VERSION",
    "LoadedConfig",
    "LoggingConfig",
    "LoggingVisualsConfig",
    "OutputConfig",
    "OutputParquetConfig",
    "OutputSchemaConfig",
    "OutputUSRConfig",
    "PWMArtifactInput",
    "PWMArtifactSetInput",
    "PWMJasparInput",
    "PWMMatrixColumns",
    "PWMMatrixCSVInput",
    "PWMMemeInput",
    "PWMMemeSetInput",
    "PWMMiningBudgetConfig",
    "PWMMiningConfig",
    "PWMSamplingConfig",
    "PWMSelectionConfig",
    "PWMSelectionPoolConfig",
    "PWMTrimmingConfig",
    "PWMUniquenessConfig",
    "PadConfig",
    "PadGcConfig",
    "PlanItem",
    "PlanSamplingConfig",
    "PlanTemplate",
    "PlotConfig",
    "PostprocessConfig",
    "PromoterMatrix",
    "PromoterMatrixPairing",
    "PromoterConstraint",
    "RegulatorConstraints",
    "RegulatorGroup",
    "ResolvedPlanItem",
    "RootConfig",
    "RunConfig",
    "RuntimeConfig",
    "SequenceConstraintAllowSelector",
    "SequenceConstraintAllowlistItem",
    "SequenceConstraintForbidKmers",
    "SequenceConstraintsConfig",
    "SamplingConfig",
    "SequenceLibraryInput",
    "SideBiases",
    "SolverConfig",
    "SUPPORTED_SCHEMA_VERSIONS",
    "USRSequencesInput",
    "expand_plan_templates",
    "load_config",
    "normalize_motif_sets",
    "resolve_outputs_scoped_path",
    "resolve_relative_path",
    "resolve_run_root",
    "resolve_run_scoped_path",
]
