job:
  name: retron_RT_combine_from_dms
  bio_type: dna

  input:
    refs: "${JOB_DIR}/../inputs/refs.csv"
    name_col: "ref_name"
    seq_col: "sequence"
    aa_col: "protein"  # optional; REF_AA.fa is handled by storage sidecar

  permute:
    protocol: "combine_aa"
    params:
      from_dataset: "${JOB_DIR}/../results/retron_Eco1_RT_wt_codon_scan/retron_Eco1_RT_wt/records.parquet"
      codon_table: "${JOB_DIR}/../inputs/codon_tables/codon_ecoli.csv"
      singles_metric_id: "llr_mean"

      select:
        mode: per_position_best
        top_global: 25
        min_delta: 0.0
        disallow_negative_best: true
        allowed_positions: []
        exclude_positions: []
        exclude_mutations: []

      combine:
        k_min: 2
        k_max: 14
        budget_total: 100000
        strategy: "random"

      codon_choice: "top"
      rng_seed: 42

  evaluate:
    metrics:
      - id: llr_mean
        evaluator: evo2_llr
        metric: log_likelihood_ratio
        params:
          model_id: evo2_7b
          device: cuda:0
          precision: bf16
          alphabet: dna
          reduction: mean
          batch_size: 128 
      - id: logits_mean
        evaluator: evo2_logits
        metric: logits_mean
        params:
          model_id: evo2_7b
          device: cuda:0
          precision: bf16
          alphabet: dna
          batch_size: 64

  output:
    dir: "${JOB_DIR}/../results/rt_combine_from_dms"

  plot:
    which:
      - ranked_variants
      - synergy_scatter
      - metric_by_mutation_count
    metric_id: llr_mean
    font_scale: 1.0
    ranked_annotate_top: 1
    ranked_summary_top_n: 100
    ranked_export_top_k: 500
    ranked_xtick_every: 1000
    sizes:
      ranked_variants: { width: 12, height: 4 }   # wider & shorter
      synergy_scatter: { width: 6, height: 6 }
      metric_by_mutation_count: { width: 6, height: 6 }
