# clustering/config.yaml

clustering:
  batch_name: "60bp_acetate"
  input_sources:
    # - dir: "densebatch_test"
    - dir: "sub6793"
    - dir: densebatch_deg2tfbs_pipeline_tfbsfetcher_heterotypic_M9_gluc_ace_top20_n10000_60bp
    # - dir: "densebatch_deg2tfbs_pipeline_tfbsfetcher_monotypic_ArcA_n2500"
    # - dir: "densebatch_deg2tfbs_pipeline_tfbsfetcher_monotypic_CRP_n2500"
    # - dir: "densebatch_deg2tfbs_pipeline_tfbsfetcher_monotypic_Lrp_n2500"
    # - dir: "latdnabatch_20250405"
    # - dir: "seqbatch_ecocyc_28_promoters"
  method: "input_source"
  add_meta_cluster_count: true
  update_in_place: true
  leiden_resolution: .8
  cluster_selection:
    num_files: 0
    order: "max"
    custom_clusters: []
  overlay_cluster_numbers: true
  umap:
    enabled: true
    plot_dimensions: [5, 5]
    alpha: 0.2
    one_hot_key: "sequence"
    # 'alpha' is deprecated when using highlight mode.
    # Instead, use background_alpha and background_size for background points,
    # and highlight_alpha and highlight_size for highlight points.
    hue:
      method: "highlight"              # Options: "leiden", "gc_content", "seq_length", "numeric", "input_source", "highlight", "type", "intra_pairwise_similarity"
      numeric_hue: None
      normalization: "robust"                       
      background_alpha: 0.05
      background_size: 2.0
      highlight_alpha: 0.8
      highlight_size: 16.0
      # highlight_dirs must be a subset of input_sources.
      highlight_dirs:
        - "sub6793"
  output_prefix: "clusterbatch_"
  analysis:
    cluster_composition: true
    cluster_composition_plot_dimensions: [14, 4]
    diversity_assessment: true
    diversity_assessment_plot_dimensions: [10, 4]
    differential_feature_analysis: true
    intra_cluster_similarity: true
  resolution_sweep:
    enabled: false
    min: 0.1
    max: 1
    step: 0.05
    replicates: 1
    random_seeds: [42]
