"""
--------------------------------------------------------------------------------
dnadesign
src/dnadesign/studies/units/eco1_rt_repack/operations/materialization/foldcheck_review/chimerax.py

ChimeraX review script writer for Eco1 fold-check structure panels.

Module Author(s): Eric J. South
--------------------------------------------------------------------------------
"""

from __future__ import annotations

import os
from pathlib import Path

from dnadesign.studies.units.eco1_rt_repack.operations.materialization.foldcheck_review.models import PanelEntry


def write_chimerax_script(
    *,
    path: Path,
    reference_local_path: Path,
    entries: list[PanelEntry],
) -> None:
    """Write a ChimeraX command script for the copied structure subset."""

    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Eco1 fold-check structure panel",
        "# Generated by dnadesign; edit a copy if manual view changes are needed.",
        "# Paths are relative to this script directory.",
        "set bgColor white",
        f"open {_relative_chimerax_path(reference_local_path, script_path=path)}",
        "rename #1 ec86kit_cryoem_reference",
    ]
    model_index = 2
    for entry in entries:
        if not Path(entry.local_model_artifact_path).exists():
            lines.append(f"# missing local structure for {entry.candidate_id}: {entry.source_model_artifact_path}")
            continue
        lines.extend(
            [
                f"open {_relative_chimerax_path(Path(entry.local_model_artifact_path), script_path=path)}",
                f"rename #{model_index} {entry.candidate_id}_{entry.selection_stratum}",
                f"matchmaker #{model_index} to #1",
            ]
        )
        model_index += 1
    lines.extend(
        [
            "color bymodel",
            "show cartoon",
            "view",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def _relative_chimerax_path(target_path: Path, *, script_path: Path) -> str:
    if not target_path.is_absolute():
        return str(target_path)
    return os.path.relpath(target_path, start=script_path.parent)
