# dnadesign/infer/config.yaml
model:
  id: evo2_7b
  device: cuda:0
  precision: bf16
  alphabet: dna

jobs:
  - id: evo_usr_demo
    operation: extract
    ingest:
      source: usr
      dataset: 60bp_dual_promoter_cpxR_Lex      # name under usr/datasets/
      root: null                                # optional; auto-detected if omitted
      field: sequence                           # column to read
      # ids: ["<optional-specific-id>", "..."]  # subset if desired
    outputs:
      - id: logits_mean
        fn: evo2.logits
        params: { pool: { method: mean, dim: 1 } }
        format: list
      - id: ll_mean
        fn: evo2.log_likelihood
        params: { method: native, reduction: mean }
        format: float
    io:
      write_back: true
      overwrite: false
