# configs/example.yaml
densegen:
  # Define multiple input sources with explicit types and paths.
  input_sources:
    - type: "deg2tfbs_pipeline_tfbsfetcher"
      name: "all_DEG_sets"
      path: "tfbsbatch_20250209_all"
    - type: "deg2tfbs_cluster_analysis"
      name: "unfiltered"
      path: "all_regs"
      clusters: ["cluster_0", "cluster_1", "cluster_2", "cluster_3"]
    - type: "deg2tfbs_cluster_analysis"
      name: "intersects_removed"
      path: "intersects_removed"
      clusters: ["cluster_0", "cluster_1", "cluster_2", "cluster_3", "cluster_4", "cluster_5"]
    - type: "pt"
      name: "seqbatch_random_tfbs"
      path: "seqbatch_random_tfbs/seqbatch_random_tfbs.pt"
      
  # Other densegen configuration options:
  output_dir: "sequences"                         
  progress_file: "progress_status.yaml"            
  solver: "GUROBI"                                 
  solver_options:
    - "Threads=16"
    - "TimeLimit=5"
  sequence_length: 100                             
  quota: 2500                                
  subsample_size: 12
  arrays_generated_before_resample: 1              
  fixed_elements:
    promoter_constraints:
      - upstream: "TTGACA"
        downstream: "TATAAT"
        upstream_pos: [10, 80]
        spacer_length: [16, 18]
    side_biases:
      left: []
      right: []
  unique_tf_only: true
  fill_gap: true
  fill_gap_end: "5prime"     
  fill_gc_min: 0.40
  fill_gc_max: 0.60

evoinference:
  data_sources:
    # Promoter engineering datasets
    - dir: seqbatch_hernandez_et_al_positive
    - dir: seqbatch_hernandez_et_al_negative
    - dir: seqbatch_hossain_et_al
    - dir: seqbatch_johns_et_al
    - dir: seqbatch_kosuri_et_al
    - dir: seqbatch_lafleur_et_al
    - dir: seqbatch_sun_yim_et_al
    - dir: seqbatch_urtecho_et_al
    - dir: seqbatch_yu_et_al
    # EcoCyc datasets
    - dir: seqbatch_ecocyc_28_promoters
    - dir: seqbatch_ecocyc_28_tfbs_set
    # RegulonDB datasets
    - dir: seqbatch_regulondb_13_promoter_set
    - dir: seqbatch_regulondb_13_promoter_FecI_set
    - dir: seqbatch_regulondb_13_promoter_FliA_set
    - dir: seqbatch_regulondb_13_promoter_RpoD_set
    - dir: seqbatch_regulondb_13_promoter_RpoE_set
    - dir: seqbatch_regulondb_13_promoter_RpoH_set
    - dir: seqbatch_regulondb_13_promoter_RpoN_set
    - dir: seqbatch_regulondb_13_promoter_RpoS_set
    - dir: seqbatch_regulondb_13_tf_ri_set
    # Randomly generated sequences
    - dir: seqbatch_random_promoters
    - dir: seqbatch_random_tfbs
    # densegen sequences
    - dir: densebatch_deg2tfbs_pipeline_tfbsfetcher_all_DEG_sets_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_unfiltered_cluster_0_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_unfiltered_cluster_1_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_unfiltered_cluster_2_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_unfiltered_cluster_3_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_0_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_1_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_2_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_3_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_4_n2500
    - dir: densebatch_deg2tfbs_cluster_analysis_intersects_removed_cluster_5_n2500

  evo_model:
    version: "evo2_7b"
    output_types:
      - type: "logits"
        pooling:            # Optional key for pooling
          method: "mean"
          dim: 1
      # - type: "embeddings"
      #   layers: ["blocks_26_mlp_l3"]
        
  overwrite_existing: false
  checkpoint_every: 100

