# configs/example.yaml

densegen:
  input_dir: "pipeline/tfbsfetcher"         # Relative to deg2tfbs package.
  output_dir: "output_sequences"            # Defines where to save outputs.
  progress_file: "progress_status.yaml"     # Minimal progress tracker file.
  solver: "GUROBI"                          # Preferred solver; falls back to CBC if necessary.
  solver_options:
    - "Threads=16"
    - "TimeLimit=20"
  sequence_length: 100                      # Defines the length of each dense array.
  quota: 5                                  # Total number of dense arrays to generate.
  subsample_size: 10
  arrays_generated_before_resample: 1       # Set >1 to generate multiple arrays per TF-TFBS sample before resampling.
  sources:
    - "tfbsbatch_20250130_heat_shock_up"    # Directory name references for data in deg2tfbs. 
    - "tfbsbatch_20250130_nutrient_lim_up"
    - "tfbsbatch_20250130_poor_carbon_acetate_up"
  fixed_elements:                           # Incorporate positional constraints into solutions.
    promoter_constraints:
      - upstream: "TTGACA"
        downstream: "TATAAT"
        upstream_pos: [20, 80]
        spacer_length: [16, 18]
    side_biases:
      left: []
      right: []
  unique_tf_only: true                     # Enforce one binding site per TF per sequence.
  fill_gap: true                           # Padding with filler sequences to match the desired length.
  fill_gap_end: "5prime"   
  fill_gc_min: 0.40
  fill_gc_max: 0.60

data_sources:               
  - name: ecocyc_promoters
    path: "sequences/EcoCyc/ecocyc_28_promoters_2025-01-23.pt"
  - name: regulondb_promoters
    path: "sequences/RegulonDB/regulondb_13_promoters_2025-01-23.pt"
