# dnadesign/nmf/config.yaml

nmf:
  batch_name: "densebatch_deg2tfbs_pipeline_tfbsfetcher_m9_acetate_tfs_n10000_subsample20_diverse"
  k_range: [2, 36]
  n_init: 10
  max_iter: 1000
  init: "nndsvdar"
  solver: "cd"
  loss: "frobenius"
  # Set encoding_mode to "positional_bins" to activate the new approach.
  encoding_mode: "positional_bins"
  positional_binning:
    enable: true        # Enable positional binning mode.
    num_bins: 10        # Number of bins to divide each sequence.
  max_motif_occupancy: 5
  strand_aware: false
  normalize_coefficients: true
  clip_h_max: 3.0
  best_k: 12
  regularization:
    enable: true
    type: "l2"
    alpha: 0.01
  plots:
    generate_heatmaps: true
    generate_motif_occurrence_heatmap: true
    generate_program_association_barplot: true
    generate_sequence_program_decomposition: false
    generate_motif_barplots: true
    generate_elbow_plot: true
    generate_riverplot: true
    generate_stability_plots: true
    generate_signature_stability_riverplot: true
  clustering:
    enable_w_clustering: true
    linkage_method: "ward"
  diagnostics:
    max_top_tfs: 10
    barplot_ncols: 4
    pick_representative_for_stackplot: true
    n_sequences_for_stackplot: 1000
  diversity_score:
    enable: true
    alpha: 0.5
    plot_across_k: true
  stability_metrics:
    enable: true
    metrics: ["frobenius", "amari", "cv", "silhouette_sum", "silhouette_mean", "cophenetic"]
    similarity_threshold: 0.6
    min_common_tfs: 3
    optimal_k_selection_method: "elbow"
