"""
--------------------------------------------------------------------------------
dnadesign
src/dnadesign/studies/studies/retron_hairpin_design/artifact_contracts/layout.py

Filesystem layout constants for Retron MSD compiler outputs.

Module Author(s): Eric J. South
--------------------------------------------------------------------------------
"""

from __future__ import annotations

REFERENCE_FILENAME = "msd_design_reference_v1.json"
CATALOG_FILENAME = "msd_design_catalog_v1.json"
BUNDLE_MANIFEST_FILENAME = "manifest.json"
BUNDLE_README_FILENAME = "README.md"
REFERENCE_INDEX_FILENAME = "reference_index.tsv"
REFERENCE_DIRNAME = "references"
LEGACY_ASSETS_DIRNAME = "assets"
SEQUENCE_MANIFEST_FILENAME = "sequence_manifest.json"
SEQUENCE_INDEX_FILENAME = "sequence_index.tsv"
MANIFEST_DIRNAME = "manifest"
MANIFEST_BUNDLE_DIRNAME = "bundle"
MANIFEST_CATALOG_DIRNAME = "catalog"
MANIFEST_CONFIGS_DIRNAME = "configs"
MANIFEST_INDEXES_DIRNAME = "indexes"
COMPOSITION_CONFIG_DIRNAME = "composition"
VARIANT_DIRNAME = "variants"
VARIANT_MANIFEST_DIRNAME = "manifest"
VARIANT_MANIFEST_COMPOSITION_DIRNAME = "composition"
VARIANT_MANIFEST_CONSTRUCT_DIRNAME = "construct"
VARIANT_MANIFEST_FOLDING_DIRNAME = "folding"
VARIANT_MANIFEST_PROVENANCE_DIRNAME = "provenance"
VARIANT_MANIFEST_REVIEWS_DIRNAME = "reviews"
VARIANT_MANIFEST_VISUAL_DIRNAME = "visual"
VARIANT_MANIFEST_SECONDARY_STRUCTURE_DIRNAME = "secondary_structure"
VARIANT_PLOTS_DIRNAME = "plots"
VARIANT_RUNTIME_DIRNAME = "runtime"
VARIANT_SEQUENCES_DIRNAME = "sequences"
CONSTRUCT_RUNTIME_DIRNAME = "construct"
DEFAULT_FLANK_5P_PREFIX = "gtcagaaaaaa"
DEFAULT_FLANK_3P_SUFFIX = "acagtaactcaga"
IGNORED_OUTPUT_FILENAMES = {".DS_Store"}
BASERENDER_CONTRACT_KIND = "nucleotide_evidence_map_render_v3"
MSD_UNIT_REPEAT_COUNT = 1
SNAPBACK_FOLDBACK_SEGMENT_ID = "snapback_foldback_geometry"


__all__ = [
    "BASERENDER_CONTRACT_KIND",
    "BUNDLE_MANIFEST_FILENAME",
    "BUNDLE_README_FILENAME",
    "CATALOG_FILENAME",
    "COMPOSITION_CONFIG_DIRNAME",
    "CONSTRUCT_RUNTIME_DIRNAME",
    "DEFAULT_FLANK_3P_SUFFIX",
    "DEFAULT_FLANK_5P_PREFIX",
    "IGNORED_OUTPUT_FILENAMES",
    "LEGACY_ASSETS_DIRNAME",
    "MANIFEST_BUNDLE_DIRNAME",
    "MANIFEST_CATALOG_DIRNAME",
    "MANIFEST_CONFIGS_DIRNAME",
    "MANIFEST_DIRNAME",
    "MANIFEST_INDEXES_DIRNAME",
    "MSD_UNIT_REPEAT_COUNT",
    "REFERENCE_DIRNAME",
    "REFERENCE_FILENAME",
    "REFERENCE_INDEX_FILENAME",
    "SEQUENCE_INDEX_FILENAME",
    "SEQUENCE_MANIFEST_FILENAME",
    "SNAPBACK_FOLDBACK_SEGMENT_ID",
    "VARIANT_DIRNAME",
    "VARIANT_MANIFEST_COMPOSITION_DIRNAME",
    "VARIANT_MANIFEST_CONSTRUCT_DIRNAME",
    "VARIANT_MANIFEST_DIRNAME",
    "VARIANT_MANIFEST_FOLDING_DIRNAME",
    "VARIANT_MANIFEST_PROVENANCE_DIRNAME",
    "VARIANT_MANIFEST_REVIEWS_DIRNAME",
    "VARIANT_MANIFEST_SECONDARY_STRUCTURE_DIRNAME",
    "VARIANT_MANIFEST_VISUAL_DIRNAME",
    "VARIANT_PLOTS_DIRNAME",
    "VARIANT_RUNTIME_DIRNAME",
    "VARIANT_SEQUENCES_DIRNAME",
]
