"""Public helper surface for generated OPAL campaign notebooks."""

from __future__ import annotations

from ...src.analysis.campaign import CampaignAnalysis
from ...src.analysis.campaign_progress import (
    assess_records_contract_for_schema,
    build_ledger_status_table,
    build_records_preview,
    cli_handoff_lines,
    read_optional_table,
    records_status_lines,
    table_status_lines,
    unavailable_table,
    x_provenance_status_lines,
)
from ...src.analysis.ledger import available_rounds, latest_round, latest_run_id, require_columns
from ...src.analysis.notebook_components import (
    build_notebook_artifact_garden_lines,
    build_notebook_artifact_garden_rows,
    build_notebook_artifact_garden_summary_rows,
    build_notebook_at_a_glance_rows,
    build_notebook_baserender_contract,
    build_notebook_baserender_contract_rows,
    build_notebook_baserender_label_rows,
    build_notebook_baserender_record_options,
    build_notebook_campaign_header_lines,
    build_notebook_campaign_summary_row,
    build_notebook_change_lines,
    build_notebook_change_rows,
    build_notebook_change_summary_rows,
    build_notebook_distrust_lines,
    build_notebook_distrust_rows,
    build_notebook_evidence_rows,
    build_notebook_metric_definition_rows,
    build_notebook_no_run_lines,
    build_notebook_plot_card_rows,
    build_notebook_plot_method_rows,
    build_notebook_plot_method_sections,
    build_notebook_run_options,
    build_notebook_run_summary_lines,
    build_notebook_status_line,
    build_notebook_trust_rows,
    build_notebook_validity_lines,
    build_notebook_validity_rows,
    build_notebook_visual_surface_model,
    compact_notebook_path,
    load_notebook_baserender_record_row,
    render_notebook_baserender_record,
    resolve_notebook_round_default,
)
from ...src.plots.config import load_plot_config, parse_enabled, parse_tags
from ...src.reporting.notebook import build_notebook_view_model
from ...src.reporting.notebook_set import build_campaign_set_notebook_view_model

__all__ = [
    "CampaignAnalysis",
    "assess_records_contract_for_schema",
    "available_rounds",
    "build_campaign_set_notebook_view_model",
    "build_ledger_status_table",
    "build_notebook_artifact_garden_lines",
    "build_notebook_artifact_garden_rows",
    "build_notebook_artifact_garden_summary_rows",
    "build_notebook_at_a_glance_rows",
    "build_notebook_baserender_label_rows",
    "build_notebook_baserender_contract",
    "build_notebook_baserender_contract_rows",
    "build_notebook_baserender_record_options",
    "build_notebook_campaign_header_lines",
    "build_notebook_campaign_summary_row",
    "build_notebook_change_lines",
    "build_notebook_change_rows",
    "build_notebook_change_summary_rows",
    "build_notebook_distrust_lines",
    "build_notebook_distrust_rows",
    "build_notebook_evidence_rows",
    "build_notebook_metric_definition_rows",
    "build_notebook_no_run_lines",
    "build_notebook_plot_card_rows",
    "build_notebook_plot_method_sections",
    "build_notebook_plot_method_rows",
    "build_notebook_run_options",
    "build_notebook_run_summary_lines",
    "build_notebook_status_line",
    "build_notebook_trust_rows",
    "build_notebook_validity_lines",
    "build_notebook_validity_rows",
    "build_notebook_view_model",
    "build_notebook_visual_surface_model",
    "build_records_preview",
    "cli_handoff_lines",
    "compact_notebook_path",
    "latest_round",
    "latest_run_id",
    "load_notebook_baserender_record_row",
    "load_plot_config",
    "parse_enabled",
    "parse_tags",
    "read_optional_table",
    "records_status_lines",
    "render_notebook_baserender_record",
    "resolve_notebook_round_default",
    "require_columns",
    "table_status_lines",
    "unavailable_table",
    "x_provenance_status_lines",
]
