"""
--------------------------------------------------------------------------------
dnadesign
src/dnadesign/notify/cli/bindings/runtime.py

Runtime command binding implementations for notify CLI.

Module Author(s): Eric J. South
--------------------------------------------------------------------------------
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def run_usr_events_watch_impl(
    *,
    deps: Any,
    provider: str | None,
    url: str | None,
    url_env: str | None,
    secret_ref: str | None,
    tls_ca_bundle: Path | None,
    events: Path | None,
    profile: Path | None,
    config: Path | None,
    workspace: str | None,
    cursor: Path | None,
    follow: bool,
    wait_for_events: bool,
    idle_timeout: float | None,
    poll_interval_seconds: float,
    stop_on_terminal_status: bool,
    on_truncate: str,
    only_actions: str | None,
    only_tools: str | None,
    progress_step_pct: int | None,
    progress_min_seconds: float | None,
    on_invalid_event: str,
    allow_unknown_version: bool,
    tool: str | None,
    run_id: str | None,
    message: str | None,
    include_args: bool | None,
    include_context: bool | None,
    include_raw_event: bool | None,
    connect_timeout: float,
    read_timeout: float,
    retry_max: int,
    retry_base_seconds: float,
    fail_fast: bool,
    spool_dir: Path | None,
    dry_run: bool,
    advance_cursor_on_dry_run: bool,
) -> None:
    deps.run_usr_events_watch_command(
        provider=provider,
        url=url,
        url_env=url_env,
        secret_ref=secret_ref,
        tls_ca_bundle=tls_ca_bundle,
        events=events,
        profile=profile,
        config=config,
        workspace=workspace,
        cursor=cursor,
        follow=follow,
        wait_for_events=wait_for_events,
        idle_timeout=idle_timeout,
        poll_interval_seconds=poll_interval_seconds,
        stop_on_terminal_status=stop_on_terminal_status,
        on_truncate=on_truncate,
        only_actions=only_actions,
        only_tools=only_tools,
        progress_step_pct=progress_step_pct,
        progress_min_seconds=progress_min_seconds,
        on_invalid_event=on_invalid_event,
        allow_unknown_version=allow_unknown_version,
        tool=tool,
        run_id=run_id,
        message=message,
        include_args=include_args,
        include_context=include_context,
        include_raw_event=include_raw_event,
        connect_timeout=connect_timeout,
        read_timeout=read_timeout,
        retry_max=retry_max,
        retry_base_seconds=retry_base_seconds,
        fail_fast=fail_fast,
        spool_dir=spool_dir,
        dry_run=dry_run,
        advance_cursor_on_dry_run=advance_cursor_on_dry_run,
        run_usr_events_watch_fn=deps.run_usr_events_watch,
        read_profile_fn=deps._read_profile,
        resolve_string_value_fn=deps._resolve_string_value,
        resolve_path_value_fn=deps._resolve_path_value,
        resolve_optional_path_value_fn=deps._resolve_optional_path_value,
        resolve_optional_string_value_fn=deps._resolve_optional_string_value,
        resolve_profile_events_source_fn=deps._resolve_profile_events_source,
        normalize_tool_name_fn=deps._normalize_setup_tool_name,
        resolve_tool_events_path_fn=deps._resolve_tool_events_path,
        resolve_tool_workspace_config_fn=deps._resolve_tool_workspace_config_path,
        resolve_usr_events_path_fn=deps._resolve_usr_events_path,
        resolve_profile_webhook_source_fn=deps._resolve_profile_webhook_source,
        default_profile_path_for_tool_fn=deps._default_profile_path_for_tool,
        resolve_cli_optional_string_fn=deps._resolve_cli_optional_string,
        resolve_webhook_url_fn=deps.resolve_webhook_url,
        resolve_tls_ca_bundle_fn=deps.resolve_tls_ca_bundle,
        validate_provider_webhook_url_fn=deps.validate_provider_webhook_url,
        split_csv_fn=deps._split_csv,
        watch_usr_events_loop_fn=deps.watch_usr_events_loop,
        validate_usr_event_fn=deps._validate_usr_event,
        status_for_action_fn=deps._status_for_action,
        event_message_fn=deps._event_message,
        event_meta_fn=deps._event_meta,
        post_with_backoff_fn=deps._post_with_backoff,
    )


def run_spool_drain_impl(
    *,
    deps: Any,
    spool_dir: Path | None,
    provider: str | None,
    url: str | None,
    url_env: str | None,
    secret_ref: str | None,
    tls_ca_bundle: Path | None,
    profile: Path | None,
    connect_timeout: float,
    read_timeout: float,
    retry_max: int,
    retry_base_seconds: float,
    fail_fast: bool,
) -> None:
    deps.run_spool_drain_command(
        spool_dir=spool_dir,
        provider=provider,
        url=url,
        url_env=url_env,
        secret_ref=secret_ref,
        tls_ca_bundle=tls_ca_bundle,
        profile=profile,
        connect_timeout=connect_timeout,
        read_timeout=read_timeout,
        retry_max=retry_max,
        retry_base_seconds=retry_base_seconds,
        fail_fast=fail_fast,
        run_spool_drain_fn=deps.run_spool_drain,
        read_profile_fn=deps._read_profile,
        resolve_cli_optional_string_fn=deps._resolve_cli_optional_string,
        resolve_path_value_fn=deps._resolve_path_value,
        resolve_profile_webhook_source_fn=deps._resolve_profile_webhook_source,
        resolve_optional_path_value_fn=deps._resolve_optional_path_value,
        resolve_webhook_url_fn=deps.resolve_webhook_url,
        resolve_tls_ca_bundle_fn=deps.resolve_tls_ca_bundle,
        validate_provider_webhook_url_fn=deps.validate_provider_webhook_url,
        format_for_provider_fn=deps.format_for_provider,
        post_with_backoff_fn=deps._post_with_backoff,
    )
