"""Versioned software resource ceilings for TriJunction design searches."""

MAX_TOEHOLD_CACHE_BYTES = 256 * 1024 * 1024
MAX_TOEHOLD_DISTANCE_LOOKUPS = 1_000_000_000
MAX_TOEHOLD_SEARCH_STATE_BYTES = 64 * 1024 * 1024
MAX_TOEHOLD_ENCODED_BASES = 64 * 1024 * 1024
MAX_TOEHOLD_DP_CELLS = 2_000_000_000

MAX_BARCODE_GENERATION_STATE_BYTES = 128 * 1024 * 1024
MAX_BARCODE_GENERATION_BASE_VISITS = 250_000_000
MAX_BARCODE_DISTANCE_CACHE_BYTES = 128 * 1024 * 1024
MAX_BARCODE_DP_CELLS = 1_000_000_000
MAX_BARCODE_SUBSET_LOOKUPS = 100_000_000
MAX_BARCODE_SUBSET_STATE_BYTES = 64 * 1024 * 1024

MAX_MATCHING_SUBSTRING_VISITS = 250_000_000
MAX_MATCHING_STATE_BYTES = 64 * 1024 * 1024

# One request may contain several independently searched physical pools. These
# aggregate limits supplement, rather than replace, the per-pool ceilings.
REQUEST_WORKLOAD_POLICY = "dnadesign.trijunction.request-workload.v1"
MAX_REQUEST_POOL_COUNT = 4_096
MAX_REQUEST_TARGET_COUNT = 100_000
MAX_REQUEST_INPUT_BASES = 256 * 1024 * 1024
MAX_REQUEST_LOCUS_COUNT = 250_000
MAX_REQUEST_TOEHOLD_CANDIDATES = 1_000_000
MAX_REQUEST_BARCODE_CANDIDATES = 4_000_000
MAX_REQUEST_TOEHOLD_ENCODED_BASES = 4 * MAX_TOEHOLD_ENCODED_BASES
MAX_REQUEST_TOEHOLD_CACHE_BYTES = 4 * MAX_TOEHOLD_CACHE_BYTES
MAX_REQUEST_TOEHOLD_DISTANCE_LOOKUPS = 4 * MAX_TOEHOLD_DISTANCE_LOOKUPS
MAX_REQUEST_TOEHOLD_DP_CELLS = 4 * MAX_TOEHOLD_DP_CELLS
MAX_REQUEST_TOEHOLD_SEARCH_STATE_BYTES = 4 * MAX_TOEHOLD_SEARCH_STATE_BYTES
MAX_REQUEST_BARCODE_GENERATION_BASE_VISITS = 4 * MAX_BARCODE_GENERATION_BASE_VISITS
MAX_REQUEST_BARCODE_GENERATION_STATE_BYTES = 4 * MAX_BARCODE_GENERATION_STATE_BYTES
MAX_REQUEST_BARCODE_ENCODED_BASES = 4 * MAX_BARCODE_DISTANCE_CACHE_BYTES
MAX_REQUEST_BARCODE_DISTANCE_CACHE_BYTES = 4 * MAX_BARCODE_DISTANCE_CACHE_BYTES
MAX_REQUEST_BARCODE_DP_CELLS = 4 * MAX_BARCODE_DP_CELLS
MAX_REQUEST_BARCODE_SUBSET_LOOKUPS = 4 * MAX_BARCODE_SUBSET_LOOKUPS
MAX_REQUEST_BARCODE_SUBSET_STATE_BYTES = 4 * MAX_BARCODE_SUBSET_STATE_BYTES
MAX_REQUEST_MATCHING_SUBSTRING_VISITS = 4 * MAX_MATCHING_SUBSTRING_VISITS
MAX_REQUEST_MATCHING_STATE_BYTES = 4 * MAX_MATCHING_STATE_BYTES
