"""
--------------------------------------------------------------------------------
dnadesign
src/dnadesign/trijunction/design/resources/limits.py

Versioned software resource ceilings for TriJunction design searches.

Module Author(s): Eric J. South
--------------------------------------------------------------------------------
"""

MAX_TOEHOLD_CACHE_BYTES = 256 * 1024 * 1024
# Two explicit streamed passes preserve the former admitted search shapes:
# one pass discovers per-trial maxima and one reads cached distances to form
# exact fixed-point weights. The DP-cell ceiling still bounds computations.
MAX_TOEHOLD_DISTANCE_LOOKUPS = 2_000_000_000
MAX_TOEHOLD_SEARCH_STATE_BYTES = 64 * 1024 * 1024
MAX_TOEHOLD_ENCODED_BASES = 64 * 1024 * 1024
MAX_TOEHOLD_DP_CELLS = 2_000_000_000

MAX_BARCODE_GENERATION_STATE_BYTES = 128 * 1024 * 1024
MAX_BARCODE_GENERATION_BASE_VISITS = 250_000_000
MAX_BARCODE_DISTANCE_CACHE_BYTES = 128 * 1024 * 1024
# The uint16 distance cache reserves 65,535 as its unevaluated sentinel.
MAX_BARCODE_DISTANCE_SEQUENCE_LENGTH = 65_534
MAX_BARCODE_DP_CELLS = 1_000_000_000
MAX_BARCODE_SUBSET_LOOKUPS = 100_000_000
MAX_BARCODE_SUBSET_STATE_BYTES = 64 * 1024 * 1024

# Peak transient work for one cache-backed pair-distance batch. Retained
# triangular caches have separate limits above.
MAX_PAIR_DISTANCE_SCRATCH_BYTES = 64 * 1024 * 1024

MAX_MATCHING_SUBSTRING_CHARACTER_VISITS = 750_000_000
MAX_MATCHING_STATE_BYTES = 64 * 1024 * 1024

# One request may contain several independently searched physical pools. These
# aggregate limits supplement, rather than replace, the per-pool ceilings.
REQUEST_WORKLOAD_POLICY = "dnadesign.trijunction.request-workload.v1"
MAX_REQUEST_POOL_COUNT = 4_096
MAX_REQUEST_TARGET_COUNT = 100_000
MAX_REQUEST_INPUT_BASES = 256 * 1024 * 1024
MAX_REQUEST_LOCUS_COUNT = 250_000
MAX_REQUEST_TOEHOLD_CANDIDATES = 1_000_000
MAX_REQUEST_BARCODE_CANDIDATES = 4_000_000
MAX_REQUEST_TOEHOLD_ENCODED_BASES = 4 * MAX_TOEHOLD_ENCODED_BASES
MAX_REQUEST_TOEHOLD_CACHE_BYTES = 4 * MAX_TOEHOLD_CACHE_BYTES
MAX_REQUEST_TOEHOLD_DISTANCE_LOOKUPS = 4 * MAX_TOEHOLD_DISTANCE_LOOKUPS
MAX_REQUEST_TOEHOLD_DP_CELLS = 4 * MAX_TOEHOLD_DP_CELLS
MAX_REQUEST_TOEHOLD_SEARCH_STATE_BYTES = 4 * MAX_TOEHOLD_SEARCH_STATE_BYTES
MAX_REQUEST_BARCODE_GENERATION_BASE_VISITS = 4 * MAX_BARCODE_GENERATION_BASE_VISITS
MAX_REQUEST_BARCODE_GENERATION_STATE_BYTES = 4 * MAX_BARCODE_GENERATION_STATE_BYTES
MAX_REQUEST_BARCODE_ENCODED_BASES = 4 * MAX_BARCODE_DISTANCE_CACHE_BYTES
MAX_REQUEST_BARCODE_DISTANCE_CACHE_BYTES = 4 * MAX_BARCODE_DISTANCE_CACHE_BYTES
MAX_REQUEST_BARCODE_DP_CELLS = 4 * MAX_BARCODE_DP_CELLS
MAX_REQUEST_BARCODE_SUBSET_LOOKUPS = 4 * MAX_BARCODE_SUBSET_LOOKUPS
MAX_REQUEST_BARCODE_SUBSET_STATE_BYTES = 4 * MAX_BARCODE_SUBSET_STATE_BYTES
MAX_REQUEST_MATCHING_SUBSTRING_CHARACTER_VISITS = 4 * MAX_MATCHING_SUBSTRING_CHARACTER_VISITS
MAX_REQUEST_MATCHING_STATE_BYTES = 4 * MAX_MATCHING_STATE_BYTES
